services:
  app:
    container_name: express_api
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - expressapi_net
    depends_on:
      - mysql
    restart: unless-stopped
    # Run a command against the development stage of the image
    command: npm run dev

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - expressapi_net      
    volumes:
      - express-mysql-data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - expressapi_net   
    restart: unless-stopped

volumes:
  express-mysql-data:
networks:
  expressapi_net:
